# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
version: 2
updates:
  # JavaScript (npm) dependencies
  - package-ecosystem: "npm" # Manages dependencies from package.json
    directory: "/" # Root folder where package.json is located
    schedule:
      interval: "weekly" # Check for updates every week
    open-pull-requests-limit: 10 # Limit the number of open PRs
    ignore:
      - dependency-name: "*" # Ignore major version updates
        update-types: ["version-update:semver-major"]

  # Python (pip) dependencies
  - package-ecosystem: "pip" # Manages dependencies from requirements.txt
    directory: "/" # Root folder where requirements.txt is located
    schedule:
      interval: "weekly" # Check for updates every week
    open-pull-requests-limit: 10 # Limit the number of open PRs
    ignore:
      - dependency-name: "*" # Ignore major version updates
        update-types: ["version-update:semver-major"]

  # GitHub Actions (CI/CD)
  - package-ecosystem: "github-actions" # Keeps GitHub Actions workflows updated
    directory: "/" # Root folder where GitHub Actions workflows are stored
    schedule:
      interval: "weekly"
